version: '3'
services:
  app:
    build: ./
    ports:
      - "3006:3006"
    expose:
      - 3006
    volumes:
      - ./:/app
      - /app/node_modules
    container_name: react-router
    env_file:
      - ./.env